Repository mario11596/autoshare_application, pull requests merged in 2022-04, with the labels that each got.

#7 Homescreen basic logic and design. Closes #1
  .idea/gradle.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/MainActivity.kt
  app/src/main/java/com/riteh/autoshare/adapters/ViewPagerAdapter.kt
  app/src/main/java/com/riteh/autoshare/model/SearchDataModel.kt
  app/src/main/java/com/riteh/autoshare/view/AddFragment.kt
  app/src/main/java/com/riteh/autoshare/view/InfoFragment.kt
  app/src/main/java/com/riteh/autoshare/view/MainActivity.kt
  app/src/main/java/com/riteh/autoshare/view/MessagesFragment.kt
  app/src/main/java/com/riteh/autoshare/view/SearchFragment.kt
  app/src/main/java/com/riteh/autoshare/view/UserFragment.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/InfoViewModel.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/MessagesViewModel.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/SearchViewModel.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/UserViewModel.kt
  app/src/main/res/color/bottom_nav_color.xml
  app/src/main/res/drawable/ic_baseline_directions_car_24.xml
  app/src/main/res/drawable/ic_baseline_info_24.xml
  app/src/main/res/drawable/ic_baseline_message_24.xml
  app/src/main/res/drawable/ic_baseline_person_24.xml
  app/src/main/res/drawable/logo.png
  app/src/main/res/drawable/logo_banner.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_fragment.xml
  app/src/main/res/layout/info_fragment.xml
  app/src/main/res/layout/messages_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/user_fragment.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: enhancement

#10 4 login and registration screen
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/model/SearchDataModel.kt
  app/src/main/java/com/riteh/autoshare/network/AuthApi.kt
  app/src/main/java/com/riteh/autoshare/network/ReemoteDataSource.kt
  app/src/main/java/com/riteh/autoshare/network/Resource.kt
  app/src/main/java/com/riteh/autoshare/repository/AuthRepository.kt
  app/src/main/java/com/riteh/autoshare/repository/BaseRepository.kt
  app/src/main/java/com/riteh/autoshare/responses/LoginResponse.kt
  app/src/main/java/com/riteh/autoshare/responses/User.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/LoginFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/RegistrationFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/base/BaseFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/base/ViewModelFactory.kt
  app/src/main/java/com/riteh/autoshare/ui/home/AddFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/InfoFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/InfoViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MainActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MessagesFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MessagesViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/SearchFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/SearchViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/UserFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/UserViewModel.kt
  app/src/main/java/com/riteh/autoshare/viewmodel/MessagesViewModel.kt
  app/src/main/res/drawable/ic_baseline_add_circle_outline_24.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_fragment.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/layout/messages_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/user_fragment.xml
  app/src/main/res/navigation/nav_auth.xml
  app/src/main/res/values/strings.xml
  build.gradle
Labels: core feature

#19 Bank cards info screen fix: added billing address
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/src/main/java/com/riteh/autoshare/ui/user/UserCard.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardActivity.kt
  app/src/main/res/layout/activity_user_card.xml
  app/src/main/res/values/strings.xml
Labels: fix

#12 Enabled to add credit card to shared preferences. Closes #5
  .idea/deploymentTargetDropDown.xml
  .idea/misc.xml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/network/RemoteDataSource.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCard.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardActivity.kt
  app/src/main/res/layout/activity_user_card.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: core feature

#21 Full search tab location and date range input functionality (to dev). Closes #3
  .idea/.name
  app/build.gradle
  app/google-services.json
  app/src/main/AndroidManifest.xml
  app/src/main/ic_launcher-playstore.png
  app/src/main/java/com/riteh/autoshare/App.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MainActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/AddFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/InfoFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/InfoViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/messages/MessagesFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/messages/MessagesViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/LocationInputActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/SearchFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/SearchViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/UserFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/UserViewModel.kt
  app/src/main/res/drawable/bottom_corners_rounded_white.xml
  app/src/main/res/drawable/ic_baseline_add_location_alt_24.xml
  app/src/main/res/drawable/ic_baseline_arrow_back_24.xml
  app/src/main/res/drawable/ic_baseline_calendar_today_24.xml
  app/src/main/res/drawable/ic_baseline_close_24.xml
  app/src/main/res/drawable/ic_baseline_location_on_24.xml
  app/src/main/res/drawable/ic_car_driving.xml
  app/src/main/res/drawable/line_horizontal.xml
  app/src/main/res/drawable/rounded_corners_box_white.xml
  app/src/main/res/layout/activity_location_input.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/add_fragment.xml
  app/src/main/res/layout/info_fragment.xml
  app/src/main/res/layout/messages_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/user_fragment.xml
  app/src/main/res/mipmap-hdpi/ic_launcher_applogo.png
  app/src/main/res/mipmap-mdpi/ic_launcher_applogo.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_applogo.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_applogo.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_applogo.png
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
  build.gradle
Labels: core feature

#23 Add user tab buttons
  app/src/main/res/drawable/ic_baseline_chevron_right_24.xml
  app/src/main/res/layout/user_fragment.xml
  app/src/main/res/values/strings.xml
Labels: core feature

#22 17 cards info screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/adapters/CardListAdapter.kt
  app/src/main/java/com/riteh/autoshare/ui/user/CardNumberFormatX.kt
  app/src/main/java/com/riteh/autoshare/ui/user/CardNumbersFormat.kt
  app/src/main/java/com/riteh/autoshare/ui/user/CvvFormat.kt
  app/src/main/java/com/riteh/autoshare/ui/user/DueDateFormat.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCard.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardInfoActivity.kt
  app/src/main/res/drawable/edit_text_border.xml
  app/src/main/res/drawable/ic_baseline_delete_forever_24.xml
  app/src/main/res/drawable/rounded_corners_box_red.xml
  app/src/main/res/layout/activity_user_card.xml
  app/src/main/res/layout/activity_user_card_info.xml
  app/src/main/res/layout/credit_card_layout.xml
  app/src/main/res/layout/top_title.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
Labels: enhancement

#28 Complete fuel prices fetching and display. Closes #15
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/adapters/FuelPricesExpandableListAdapter.kt
  app/src/main/java/com/riteh/autoshare/data/dataholders/FuelPriceHolder.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/FuelPricesActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/InfoFragment.kt
  app/src/main/java/com/riteh/autoshare/util/FuelPriceFetcher.kt
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_down_24.xml
  app/src/main/res/drawable/ic_baseline_keyboard_arrow_up_24.xml
  app/src/main/res/drawable/rounded_corners_box_white.xml
  app/src/main/res/drawable/selector_expandable_list.xml
  app/src/main/res/layout/activity_fuel_prices.xml
  app/src/main/res/layout/elv_group.xml
  app/src/main/res/layout/elv_item.xml
  app/src/main/res/layout/info_fragment.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/mipmap-hdpi/ic_adriaoil.png
  app/src/main/res/mipmap-hdpi/ic_crodux.png
  app/src/main/res/mipmap-hdpi/ic_ferotom.png
  app/src/main/res/mipmap-hdpi/ic_ina.png
  app/src/main/res/mipmap-hdpi/ic_lukoil.png
  app/src/main/res/mipmap-hdpi/ic_mitea.png
  app/src/main/res/mipmap-hdpi/ic_petrol.png
  app/src/main/res/mipmap-mdpi/ic_adriaoil.png
  app/src/main/res/mipmap-mdpi/ic_crodux.png
  app/src/main/res/mipmap-mdpi/ic_ferotom.png
  app/src/main/res/mipmap-mdpi/ic_ina.png
  app/src/main/res/mipmap-mdpi/ic_lukoil.png
  app/src/main/res/mipmap-mdpi/ic_mitea.png
  app/src/main/res/mipmap-mdpi/ic_petrol.png
  app/src/main/res/mipmap-xhdpi/ic_adriaoil.png
  app/src/main/res/mipmap-xhdpi/ic_crodux.png
  app/src/main/res/mipmap-xhdpi/ic_ferotom.png
  app/src/main/res/mipmap-xhdpi/ic_ina.png
  app/src/main/res/mipmap-xhdpi/ic_lukoil.png
  app/src/main/res/mipmap-xhdpi/ic_mitea.png
  app/src/main/res/mipmap-xhdpi/ic_petrol.png
  app/src/main/res/mipmap-xxhdpi/ic_adriaoil.png
  app/src/main/res/mipmap-xxhdpi/ic_crodux.png
  app/src/main/res/mipmap-xxhdpi/ic_ferotom.png
  app/src/main/res/mipmap-xxhdpi/ic_ina.png
  app/src/main/res/mipmap-xxhdpi/ic_lukoil.png
  app/src/main/res/mipmap-xxhdpi/ic_mitea.png
  app/src/main/res/mipmap-xxhdpi/ic_petrol.png
  app/src/main/res/mipmap-xxxhdpi/ic_adriaoil.png
  app/src/main/res/mipmap-xxxhdpi/ic_crodux.png
  app/src/main/res/mipmap-xxxhdpi/ic_ferotom.png
  app/src/main/res/mipmap-xxxhdpi/ic_ina.png
  app/src/main/res/mipmap-xxxhdpi/ic_lukoil.png
  app/src/main/res/mipmap-xxxhdpi/ic_mitea.png
  app/src/main/res/mipmap-xxxhdpi/ic_petrol.png
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: core feature

#26 added comments on some functions
  app/src/main/java/com/riteh/autoshare/adapters/CardListAdapter.kt
  app/src/main/java/com/riteh/autoshare/network/AuthApi.kt
  app/src/main/java/com/riteh/autoshare/network/RemoteDataSource.kt
  app/src/main/java/com/riteh/autoshare/network/Resource.kt
  app/src/main/java/com/riteh/autoshare/repository/AuthRepository.kt
  app/src/main/java/com/riteh/autoshare/ui/Utils.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/user/CardNumberFormatX.kt
  app/src/main/java/com/riteh/autoshare/ui/user/CardNumbersFormat.kt
  app/src/main/java/com/riteh/autoshare/ui/user/DueDateFormat.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/user/UserCardInfoActivity.kt
Labels: documentation

#29 27 splash screen
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/SplashActivity.kt
  app/src/main/java/com/riteh/autoshare/network/RemoteDataSource.kt
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/fragment_registration.xml
Labels: core feature

#31 24 improving code legibility
  app/src/main/java/com/riteh/autoshare/adapters/CardListAdapter.kt
Labels: documentation

#33 25 Login and registration screen design enhancements
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/ui/auth/LoginFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/RegistrationFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/AddFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/InfoFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/InfoViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MessagesFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/MessagesViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/SearchFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/SearchViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/UserFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/UserViewModel.kt
  app/src/main/res/drawable/background.png
  app/src/main/res/drawable/ic_baseline_mail_outline_24.xml
  app/src/main/res/drawable/ic_baseline_visibility_24.xml
  app/src/main/res/drawable/ic_baseline_visibility_off_24.xml
  app/src/main/res/drawable/ic_baseline_vpn_key_24.xml
  app/src/main/res/drawable/rounded_corners_box_darker_white.xml
  app/src/main/res/drawable/rounded_corners_box_outline_white.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/fragment_login.xml
  app/src/main/res/layout/fragment_registration.xml
  app/src/main/res/navigation/nav_auth.xml
  app/src/main/res/raw/animation_cars.json
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/main/res/values/themes.xml
Labels: enhancement
