Repository mario11596/autoshare_application, pull requests merged in 2022-06, with the labels that each got.

#47 enabling the display of all vehicles in the search. Closes #40
  app/src/main/java/com/riteh/autoshare/adapters/CarListAdapter.kt
  app/src/main/java/com/riteh/autoshare/data/api/APIRequest.kt
  app/src/main/java/com/riteh/autoshare/network/VehicleApi.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/CarsListActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/LocationInputActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/SearchFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/SearchViewModel.kt
  app/src/main/res/drawable/ic_message.xml
  app/src/main/res/layout/car_layout.xml
  app/src/main/res/layout/messages_fragment.xml
  app/src/main/res/values/strings.xml
Labels: core feature

#48 37 vehicle details and renting screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/adapters/CarListAdapter.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/CarsListActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/VehicleDetailsRentingActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/search/VehicleRentViewModel.kt
  app/src/main/res/drawable/ic_car_door_svgrepo.xml
  app/src/main/res/drawable/ic_car_seat_svgrepo_com.xml
  app/src/main/res/drawable/ic_car_svgrepo_com.xml
  app/src/main/res/drawable/ic_gas_station_svgrepo.xml
  app/src/main/res/layout/fragment_rent_completed.xml
  app/src/main/res/layout/vehicle_details_renting.xml
  app/src/main/res/values/strings.xml
Labels: core feature

#49 App-wide UX/UI enhancements
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/riteh/autoshare/adapters/VehicleListAdapter.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/WeatherActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/info/WeatherFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/UserCardInfoActivity.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/BrandFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/DetailsFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/ExtraInfoBooleansFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/ExtraInfoFillInFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/ExtraInfoSelectableFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/user/vehicles/ModelFragment.kt
  app/src/main/res/drawable/ic_rent.xml
  app/src/main/res/layout/activity_fuel_prices.xml
  app/src/main/res/layout/activity_location_input.xml
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/layout/activity_user_card.xml
  app/src/main/res/layout/activity_user_card_info.xml
  app/src/main/res/layout/activity_user_information.xml
  app/src/main/res/layout/activity_user_update.xml
  app/src/main/res/layout/activity_vehicle_list.xml
  app/src/main/res/layout/activity_vehicles_list.xml
  app/src/main/res/layout/activity_weather.xml
  app/src/main/res/layout/add_fragment.xml
  app/src/main/res/layout/credit_card_layout.xml
  app/src/main/res/layout/fragment_brand.xml
  app/src/main/res/layout/fragment_date.xml
  app/src/main/res/layout/fragment_details.xml
  app/src/main/res/layout/fragment_extra_info_booleans.xml
  app/src/main/res/layout/fragment_extra_info_fill_in.xml
  app/src/main/res/layout/fragment_extra_info_selectable.xml
  app/src/main/res/layout/fragment_location.xml
  app/src/main/res/layout/fragment_model.xml
  app/src/main/res/layout/fragment_price.xml
  app/src/main/res/layout/fragment_vehicle_select.xml
  app/src/main/res/layout/search_fragment.xml
  app/src/main/res/layout/user_fragment.xml
  app/src/main/res/layout/user_vehicle_items_layout.xml
  app/src/main/res/layout/vehicle_rent_layout.xml
  app/src/main/res/layout/weather_fragment.xml
  app/src/main/res/values/dimen.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#50 43 vehicles for rent - creating an availability functionality
  app/src/main/java/com/riteh/autoshare/adapters/VehiclesForRentListAdapter.kt
  app/src/main/java/com/riteh/autoshare/network/VehicleApi.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/AddingUnsuccessfulFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/DateFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/PriceFragment.kt
  app/src/main/res/layout/fragment_adding_unsuccessful.xml
  app/src/main/res/navigation/nav_add_tab.xml
  app/src/main/res/values/strings.xml
Labels: enhancement, core feature

#52 43 vehicles for rent - enhancements
  app/src/main/java/com/riteh/autoshare/data/dataholders/VehicleFull.kt
  app/src/main/java/com/riteh/autoshare/data/dataholders/VehicleFullListItem.kt
  app/src/main/java/com/riteh/autoshare/network/VehicleApi.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/AddViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/DateFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/home/add/VehicleSelectFragment.kt
  app/src/main/res/drawable/ic_empty.xml
  app/src/main/res/layout/fragment_vehicle_select.xml
  app/src/main/res/values/strings.xml
Labels: enhancement

#56 Fix signup response type and intent to MainActivity. Closes #55
  app/src/main/java/com/riteh/autoshare/network/AuthApi.kt
  app/src/main/java/com/riteh/autoshare/responses/AuthResponse.kt
  app/src/main/java/com/riteh/autoshare/responses/SignUpResponse.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/LoginFragment.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/RegistrationFragment.kt
Labels: fix

#57 53 testing api calls - auth
  app/build.gradle
  app/src/main/java/com/riteh/autoshare/App.kt
  app/src/test/java/com/riteh/autoshare/AuthenticationManagerTest.kt
  app/src/test/java/com/riteh/autoshare/ExampleUnitTest.kt
  app/src/test/java/com/riteh/autoshare/data/LoginBody.kt
  app/src/test/java/com/riteh/autoshare/data/SignUpBody.kt
  app/src/test/java/com/riteh/autoshare/util/MockResponseFileReader.kt
  app/src/test/java/com/riteh/autoshare/util/managers/AuthenticationManager.kt
  app/src/test/resources/auth_fail.json
  app/src/test/resources/auth_success.json
Labels: testing

#58 54 method unit tests
  app/build.gradle
  app/src/main/java/com/riteh/autoshare/ui/auth/AuthViewModel.kt
  app/src/main/java/com/riteh/autoshare/ui/auth/RegistrationFragment.kt
  app/src/test/java/com/riteh/autoshare/ui/auth/AuthViewModelTest.kt
Labels: testing
